name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  host-build:
    runs-on: ubuntu-latest
    name: GCC v9.3.0
    steps:
      - uses: actions/checkout@v2
      - name: Configure and build
        run: |
          cmake -Bbuild \
            -DCMAKE_CXX_STANDARD:STRING="17" \
            -DKokkos_ENABLE_SERIAL=ON \
            -DKokkos_ENABLE_OPENMP=OFF \
            -DKokkos_ENABLE_CUDA=OFF \
            -DKokkos_ENABLE_HIP=OFF \
            -DKokkos_ENABLE_OPENMPTARGET=OFF .
          cmake --build build -- -j $(nproc)
      - name: Execute
        run: |
          cd build
          ./exw_virtuals
  cuda-build:
    runs-on: ubuntu-latest
    name: NVIDIA CUDA v11.0 + GCC v9.3.0
    steps:
      - uses: actions/checkout@v2
      - name: Prepare CUDA environment
        run: |
          export DEBIAN_FRONTEND=noninteractive
          wget -q -O - https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub | sudo apt-key add -
          echo "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64 /" | sudo tee /etc/apt/sources.list.d/cuda.list
          echo "deb https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64 /" | sudo tee /etc/apt/sources.list.d/nvidia-ml.list
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
              libopenmpi-dev cuda-command-line-tools-11-0 cuda-compiler-11-0 cuda-minimal-build-11-0 cuda-nvml-dev-11-0 cuda-nvtx-11-0
      - name: Configure and build
        run: |
          export PATH=/usr/local/nvidia/bin:/usr/local/cuda-11.0/bin:${PATH}
          export LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda-11.0/lib:${LD_LIBRARY_PATH}
          cmake -Bbuild \
            -DCMAKE_CXX_STANDARD:STRING="17" \
            -DKokkos_ENABLE_SERIAL=ON \
            -DKokkos_ENABLE_OPENMP=OFF \
            -DKokkos_ENABLE_CUDA=ON \
            -DKokkos_ENABLE_HIP=OFF \
            -DKokkos_ENABLE_OPENMPTARGET=OFF \
            -DKokkos_ENABLE_CUDA_LAMBDA=ON \
            -DKokkos_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE=ON \
            -DKokkos_ARCH_VOLTA70=ON .
          cmake --build build -- -j $(nproc)
